name: Continuous Integration

on:
  push:
    branches:
      - "main"
    tags:
      - "*"
  pull_request:
    branches:
      - "main"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        name: Setup Rust
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - uses: actions-rs/cargo@v1
        name: fmt
        with:
          command: fmt
          args: --all -- --check
      - uses: actions-rs/cargo@v1
        name: clippy
        with:
          command: clippy
          args: --all-targets -- --deny warnings
      - uses: actions-rs/cargo@v1
        name: test
        with:
          command: test

  build_for_linux:
    name: Build for Linux
    needs: [check]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          default: true
      - name: Build Wheels
        uses: messense/maturin-action@v1
        with:
          target: x86_64
          manylinux: auto
          #args: -i python${{ matrix.python-version }} --release --out dist --no-sdist
          args: --release --out dist --no-sdist
      - name: Upload Wheels Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: dist

  build_for_windows:
    name: Build for Windows
    needs: [check]
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          default: true
      - name: Build Wheels
        uses: messense/maturin-action@v1
        with:
          target: x64
          args: --release --out dist --no-sdist
      - name: Upload Wheels Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: dist

  build_for_macos:
    name: Build for MacOS
    needs: [check]
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          default: true
      - name: Build Wheels
        uses: messense/maturin-action@v1
        with:
          target: x86_64
          args: --release --out dist --no-sdist
      - name: Upload Wheels Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: dist

  publish_on_pypi:
    name: Publish
    needs: [build_for_linux, build_for_macos, build_for_windows]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: wheels
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Publish on TestPyPI
        if: github.ref == 'refs/head/main'
        env:
          TWINE_USERNAME: LSchueler
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }}
        run: |
          pip install --upgrade twine
          twine upload --repository testpypi --skip-existing *
      - name: Publish on PyPI
        if: startsWith(github.ref, 'refs/tags')
        env:
          TWINE_USERNAME: LSchueler
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          pip install --upgrade twine
          twine upload --skip-existing *

  #publish_on_pypi:
    #name: Publish
    ##needs: [build_for_linux, build_for_macos, build_for_windows]
    #needs: build_for_macos
    #runs-on: ubuntu-latest
    #steps:
      #- uses: actions/download-artifact@v2
        #with:
          #name: wheels
      #- name: Publish on TestPyPI
        ##if: github.ref == 'refs/head/main'
        #uses: pypa/gh-action-pypi-publish@release/v1
        #with:
          #user: LSchueler
          #password: ${{ secrets.test_pypi_password }}
          #repository_url: https://test.pypi.org/simple/
          #skip_existing: true
      #- name: Publish on PyPI
        #if: startsWith(github.ref, 'refs/tags')
        #uses: pypa/gh-action-pypi-publish@release/v1
        #with:
          #user: LSchueler
          #password: ${{ secrets.pypi_password }}

  #This will probably never be needed, but who knows...
  #publish_on_crates:
    #needs: [check]
    #runs-on: ubuntu-latest
    #steps:
      #- uses: actions/checkout@v2
      #- uses: actions-rs/toolchain@v1
        #with:
          #toolchain: stable
          #override: true

      #- name: Dry Run Publish
        ##only on main branch
        #if: github.ref == 'refs/heads/main'
        #uses: katyo/publish-crates@v1
        #with:
          #dry-run: true

      #- name: Dry Run Publish
        ##only if tagged
        #if: startsWith(github.ref, 'refs/tags')
        #uses: katyo/publish-crates@v1
        #with:
          #registry-token: ${{ secrets.CRATES_TOKEN }}
